Add a small check that the demo played through.
Sadly it isn't possible to check the exit code, since `-timedemo` exits
with an error even when no error has occurred. But we can at least
check for the message that is printed at the end of a `-timedemo`
playback.

diff --git a/playthru/testrunner b/playthru/testrunner
--- a/playthru/testrunner
+++ b/playthru/testrunner
@@ -30,6 +30,12 @@ $SOURCE_PORT -iwad "$iwad" \
              -noblit -noautoload -nogui -nograbmouse \
              -statdump $tmp/statdump.txt "$@" >$tmp/log.txt 2>&1 || true
 
+if ! grep -q "timed [0-9]* gametics in" $tmp/log.txt; then
+	echo "Expected -timedemo line not found in log:" >&2
+	cat $tmp/log.txt >&2
+	exit 1
+fi
+
 #cat $tmp/log.txt 1>&2
 
 cat $tmp/statdump.txt
